on: push
permissions:
  contents: write
jobs:
  spotless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Check Spotless
        id: spotlessCheck
        continue-on-error: true
        run: ./gradlew spotlessChecky
      - name: Apply and Commit Linted File
        if: ${{ steps.spotlessCheck.outcome == 'failure' }}
        run: |
          ./gradlew spotlessApply
          git config --global user.name 'Actions Bot'
          git config --global user.email 'actions-bot@users.noreply.github.com'
          git commit -am "Automated Spotless Apply"
          git push

      
